name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.0
  geolocator: ^11.0.0
  fl_chart: ^0.66.2
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  google_maps_flutter: ^2.6.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  # ✅ AJOUT OBLIGATOIRE POUR LES ANIMATIONS MÉTÉO
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ✅ ASSETS LOTTIE (CORRECT)
  assets:
    - assets/lottie/
